[package]
name = "aurora-eth-connector"
version = "0.1.0"
authors = ["Aurora Labs <hello@aurora.dev>"]
edition = "2021"
description = ""
documentation = ""
readme = true
homepage = "https://github.com/aurora-is-near/aurora-fungible-token"
repository = "https://github.com/aurora-is-near/aurora-fungible-token"
license = "CC0-1.0"
publish = false
autobenches = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = "4.0.0"
aurora-engine-types = { git = "https://github.com/aurora-is-near/aurora-engine.git", branch = "develop", default-features = false }
primitive-types = { version = "0.10.0", default-features = false, features = ["rlp", "impl-serde"] }
serde = "1"
serde_json = "1"
hex = "0.4.3"

[dev-dependencies]

[features]
log = []
integration-test = ["log"]
mainnet = ["log"]
testnet = ["log"]
