---
on:
  push:
    branches:
      - master
      - develop
  pull_request:

name: Tests
jobs:
  test:
    name: Test suite (mainnet, testnet)
    runs-on: [self-hosted, heavy]
    steps:
      - name: os
        run: uname -a

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
